export const sampleSnapshot = {
  sessions: [
    {
      id: "claude-demo",
      provider: "claude-code",
      projectName: "Agent Nudge",
      status: "active",
      lastSeenAt: new Date(Date.now() - 80_000).toISOString(),
      activeTask: {
        summary: "Refining cache invalidation",
        paths: ["src/lib/cache.ts"],
        tags: ["cache", "redis"],
      },
    },
    {
      id: "codex-demo",
      provider: "codex",
      projectName: "Agent Nudge",
      status: "active",
      lastSeenAt: new Date(Date.now() - 24_000).toISOString(),
      activeTask: {
        summary: "Implementing cache adapter",
        paths: ["src/lib/cache.ts"],
        tags: ["cache", "redis"],
      },
    },
    {
      id: "opencode-47",
      provider: "opencode",
      projectName: "Agent Nudge",
      status: "idle",
      lastSeenAt: new Date(Date.now() - 18 * 60_000).toISOString(),
      activeTask: {
        summary: "Documentation review",
        paths: ["docs/PROTOCOL.md"],
        tags: ["docs"],
      },
    },
  ],
  facts: [],
  events: [],
  nudges: [
    {
      id: "nudge-conflict",
      factId: "fact-conflict",
      recipientSessionId: "codex-demo",
      projectId: "project-agent-nudge",
      title: "Claude is editing cache.ts",
      body: "Another active agent has claimed the same file. Coordinate before writing.\nAffected: src/lib/cache.ts",
      deliveryClass: "BLOCK",
      state: "queued",
      relevanceScore: 140,
      relevanceFactors: [
        {
          code: "file-claim",
          label: "Active edit conflict",
          score: 60,
          evidence: "src/lib/cache.ts",
        },
        {
          code: "exact-path",
          label: "Exact path overlap",
          score: 45,
          evidence: "src/lib/cache.ts",
        },
        {
          code: "same-project",
          label: "Same project",
          score: 25,
          evidence: "Agent Nudge",
        },
        {
          code: "source",
          label: "Evidence attached",
          score: 10,
          evidence: "Claude session receipt",
        },
      ],
      whyNow: "BLOCK: active edit conflict + exact path overlap",
      sourceRefs: [
        {
          type: "hook-event",
          label: "Claude session receipt · 8 minutes ago",
          filePath: "src/lib/cache.ts",
        },
      ],
      createdAt: new Date(Date.now() - 8 * 60_000).toISOString(),
      expiresAt: new Date(Date.now() + 86_400_000).toISOString(),
      dedupeKey: "demo",
      correlationId: "demo",
      traceId: "demo",
      extensionMetadata: {},
    },
    {
      id: "nudge-decision",
      factId: "fact-decision",
      recipientSessionId: "codex-demo",
      projectId: "project-agent-nudge",
      title: "Session storage decision changed",
      body: "Use signed cookies, not localStorage, for session state.\nAffected: src/auth/session.ts",
      deliveryClass: "ACT_NOW",
      state: "delivered",
      relevanceScore: 115,
      relevanceFactors: [
        {
          code: "exact-path",
          label: "Exact path overlap",
          score: 45,
          evidence: "src/auth/session.ts",
        },
        {
          code: "same-project",
          label: "Same project",
          score: 25,
          evidence: "Agent Nudge",
        },
        {
          code: "changed-decision",
          label: "Decision affects current work",
          score: 20,
          evidence: "Session storage decision changed",
        },
      ],
      whyNow: "ACT_NOW: exact path overlap + same project",
      sourceRefs: [
        {
          type: "user-decision",
          label: "Architecture decision · verified",
          filePath: "src/auth/session.ts",
        },
      ],
      createdAt: new Date(Date.now() - 18 * 60_000).toISOString(),
      expiresAt: new Date(Date.now() + 86_400_000).toISOString(),
      dedupeKey: "demo2",
      correlationId: "demo2",
      traceId: "demo2",
      extensionMetadata: {},
    },
    {
      id: "nudge-failure",
      factId: "fact-failure",
      recipientSessionId: "codex-demo",
      projectId: "project-agent-nudge",
      title: "Redis caching approach failed",
      body: "Integration tests exposed stale reads after invalidation. Do not repeat without addressing the receipt.\nAffected: src/lib/cache.ts",
      deliveryClass: "ACT_NOW",
      state: "acknowledged",
      relevanceScore: 115,
      relevanceFactors: [
        {
          code: "exact-path",
          label: "Exact path overlap",
          score: 45,
          evidence: "src/lib/cache.ts",
        },
        {
          code: "failure-risk",
          label: "Previously failed approach",
          score: 20,
          evidence: "Redis caching approach failed",
        },
      ],
      whyNow: "ACT_NOW: exact path overlap + previously failed approach",
      sourceRefs: [
        {
          type: "test-run",
          label: "integration/cache.test.ts · 3 failures",
          filePath: "src/lib/cache.ts",
        },
      ],
      createdAt: new Date(Date.now() - 42 * 60_000).toISOString(),
      expiresAt: new Date(Date.now() + 86_400_000).toISOString(),
      dedupeKey: "demo3",
      correlationId: "demo3",
      traceId: "demo3",
      extensionMetadata: {},
    },
  ],
  metrics: {
    activeAgents: 2,
    delivered: 2,
    acknowledged: 1,
    conflictsPrevented: 1,
    queued: 1,
  },
};
